/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.DiseaseInfoDAO;
import model.to.DiseaseInfoTo;
import utility.CommonOperations;
import utility.Validations;

/**
 *
 * @author HP
 */
public class AddDiseaseDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddDiseaseDetails
     */
    public AddDiseaseDetails() {
        initComponents();
        setSize(1000, 600);
        setLocation(400, 100);
    }

    public AddDiseaseDetails(DiseaseInfoTo record) {
        this();
        if (record != null) {
            jtfdiseaseid.setText(record.getDisease_id());
            jtfdiseasename.setText(record.getDisease_name());
            jtfdescription.setText(record.getDescription());
            setTitle("Edit Disease details");
            btnsave.setText("UPDATE DISEASES DETAILS");
            jtfdiseaseid.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfdiseaseid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfdescription = new javax.swing.JTextField();
        jtfdiseasename = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Disease Details");

        jtfdiseaseid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Disease Description");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter Disease Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Enter Disease Name");

        jtfdescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtfdiseasename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsave.setText("ADD NEW DISEASE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfdescription, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(jtfdiseasename)
                            .addComponent(jtfdiseaseid)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfdiseaseid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfdiseasename, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jtfdescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String diseaseid = jtfdiseaseid.getText();
        String diseasename = jtfdiseasename.getText();
        String description = jtfdescription.getText();
        String message = "";
        if (Validations.isEmpty(diseaseid) || Validations.isEmpty(diseasename) || Validations.isEmpty(description)) {
            message += "Please fill all fields";
        } else {
            DiseaseInfoTo record = new DiseaseInfoTo();
            record.setDisease_id(diseaseid);
            record.setDisease_name(diseasename);
            record.setDescription(description);
            DiseaseInfoDAO action = new DiseaseInfoDAO();
            if (btnsave.getText().contains("ADD")) {
                if (action.insertRecord(record)) {
                    message += " New Disease is added to the system database";
                    JInternalFrame[] allframe = getDesktopPane().getAllFrames();
                    if (allframe != null) {
                        for (JInternalFrame jif : allframe) {
                            if(jif instanceof ViewDiseases){
                                ((ViewDiseases)jif).bindTableDetails();
                                break;
                            }
                        }
                    }
                } else {
                    message += " Insertion failure" + action.getErrormessage();
                }
            } else if (btnsave.getText().contains("UPDATE")) {
                if (action.updateRecord(record)) {
                    message += " Disease detail is updated in system database";
                } else {
                    message += " updation failure" + action.getErrormessage();
                }
                CommonOperations.openInternalFrame(getDesktopPane(), new ViewDiseases());
                dispose();
            } else {
                message += "invalid operation";
            }   
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfdescription;
    private javax.swing.JTextField jtfdiseaseid;
    private javax.swing.JTextField jtfdiseasename;
    // End of variables declaration//GEN-END:variables
}
