/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.util.Locale;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.FloorInfoDAO;
import model.to.FloorInfoTo;
import utility.CommonOperations;
import utility.Validations;

/**
 *
 * @author HP
 */
public class AddFloorDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form FloorDetails
     */
    public AddFloorDetails() {
        initComponents();
        setSize(1000, 600);
        setLocation(400, 100);
    }

    public AddFloorDetails(FloorInfoTo record) {
        this();
        if (record != null) {
            jtffloorid.setText(record.getFloor_id());
            jtffloortype.setText(record.getFloor_type());
            setTitle("Edit floor details");
            btnsave.setText("UPDATE FLOOR DETAILS");
            jtffloorid.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtffloortype = new javax.swing.JTextField();
        jtffloorid = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Floor Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Floor Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter Floor ID");

        jtffloortype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtffloorid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsave.setText("ADD NEW FLOOR");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtffloorid, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtffloortype, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtffloorid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtffloortype, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String floorid = jtffloorid.getText();
        String floortype = jtffloortype.getText();
        String message = "";
        if (Validations.isEmpty(floorid) || Validations.isEmpty(floortype)) {
            message += "Please fill all fields";
        } else {
            FloorInfoTo record = new FloorInfoTo();
            record.setFloor_id(floorid);
            record.setFloor_type(floortype);
            FloorInfoDAO action = new FloorInfoDAO();
            if (btnsave.getText().contains("ADD")) {
                if (action.insertRecord(record)) {
                    message += " Floor type is added to the system database";
                    JInternalFrame[] allframe = getDesktopPane().getAllFrames();
                    if (allframe != null) {
                        for (JInternalFrame jif : allframe) {
                            if(jif instanceof ViewFloor){
                                ((ViewFloor)jif).bindTableDetails();
                                break;
                            }
                        }
                    }
                } else {
                    message += " Insertion failure" + action.getErrormessage();
                }
            } else if (btnsave.getText().contains("UPDATE")) {
                if (action.updateRecord(record)) {
                    message += " Floor type is updated in system database";
                } else {
                    message += " updation failure" + action.getErrormessage();
                }
                CommonOperations.openInternalFrame(getDesktopPane(), new ViewFloor());
                dispose();
            } else {
                message += "invalid operation";
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtffloorid;
    private javax.swing.JTextField jtffloortype;
    // End of variables declaration//GEN-END:variables
}
