/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.DiseaseInfoDAO;
import model.dao.PatientDiseaseDAO;
import model.dao.PatientInfoDAO;
import model.to.DiseaseInfoTo;
import model.to.PatientDiseaseTo;
import model.to.PatientInfoTo;
import utility.Validations;

/**
 *
 * @author HP
 */
public class EditPatientDisease extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditPatientDisease
     */
    int sno;
    public EditPatientDisease() {
        initComponents();
        setSize(1000, 600);
        setLocation(400, 100);
        jcbdiseaseid.removeAllItems();
        jcbdiseaseid.addItem("select any disease ID");
        List<DiseaseInfoTo> disease = new DiseaseInfoDAO().getAllRecord();
        if (disease != null && disease.size() > 0) {
            for (DiseaseInfoTo dt : disease) {
                jcbdiseaseid.addItem(dt);
            }
        }

    }
    public EditPatientDisease(PatientDiseaseTo record){
        this();
        if(record!=null){
            sno=record.getSr_no();
            for (int i = 1; i < jcbdiseaseid.getItemCount(); i++) {
                DiseaseInfoTo dt = (DiseaseInfoTo) jcbdiseaseid.getItemAt(i);
                if (dt.getDisease_id().equals(record.getDisease_id())) {
                    jcbdiseaseid.setSelectedIndex(i);
                    break;
                }
            }
            jtfpatientid.setText(String.valueOf(record.getPatient_id()));
            jtfhistory.setText(record.getHistory());
            jtfpatientid.setEditable(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfpatientid = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jcbdiseaseid = new javax.swing.JComboBox();
        jtfhistory = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Edit Patient Disease Details");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Choose Disease Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Enter Patient Id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter Patient History");

        jtfpatientid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfpatientid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsave.setText("UPDATE PATIENT DISEASE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jcbdiseaseid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbdiseaseid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtfhistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfpatientid)
                    .addComponent(jcbdiseaseid, 0, 387, Short.MAX_VALUE)
                    .addComponent(jtfhistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbdiseaseid, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        boolean allvalid = true;
        String message = "";
        String history = jtfpatientid.getText();
        if (jcbdiseaseid.getSelectedIndex() == 0) {
            allvalid = false;
            message += "Please choose disease Id\n\n";
        }
        if (Validations.isEmpty(history)) {
            allvalid = false;
            message = "Please fill detail about patient history \n\n";
        }
        if (allvalid) {
            PatientDiseaseTo record = new PatientDiseaseTo();
            record.setHistory(history);
            int pid=Integer.parseInt(jtfpatientid.getText());
            record.setPatient_id(pid);
            DiseaseInfoTo dt = (DiseaseInfoTo) jcbdiseaseid.getSelectedItem();
            record.setDisease_id(dt.getDisease_id());
            PatientDiseaseDAO action = new PatientDiseaseDAO();
            record.setSr_no(sno);
            if (action.updatRecord(record)) {
                message += "patient disease is updated in system";
                jcbdiseaseid.setSelectedIndex(0);
            } else {
                message += "updation failure" + action.getErrormessage();
            }
        }
        if (allvalid) {
            JOptionPane.showMessageDialog(this, message);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jcbdiseaseid;
    private javax.swing.JTextField jtfhistory;
    private javax.swing.JTextField jtfpatientid;
    // End of variables declaration//GEN-END:variables
}
