/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.DiseaseInfoDAO;
import model.to.DiseaseInfoTo;
import utility.CommonOperations;

/**
 *
 * @author HP
 */
public class ViewDiseases extends javax.swing.JInternalFrame {

    List<DiseaseInfoTo> alldiseases;
    private int srow;
    private JPopupMenu popup;

    public ViewDiseases() {
        initComponents();
        setSize(1000, 600);
        setLocation(400, 150);
        bindTableDetails();
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete Record");
        deleteitem.setFont(new Font("Arial", Font.BOLD, 20));
        JMenuItem edititem = new JMenuItem("Edit Record");
        edititem.setFont(new Font("Arial", Font.BOLD, 20));
        try {
            ImageIcon icon1;
            icon1 = new ImageIcon(getClass().getResource("/adminui/delete.png"));
            ImageIcon icon2;
            icon2 = new ImageIcon(getClass().getResource("/adminui/edit.png"));
            deleteitem.setIcon(icon1);
            edititem.setIcon(icon2);
        } catch (Exception ex) {
        }
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        edititem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }
    public void deleteRecord() {
        if (srow != -1 && alldiseases != null && srow < alldiseases.size()) {
            int result = JOptionPane.showConfirmDialog(this, "are you sure you want to remove this record?", "Message from system", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                DiseaseInfoTo ft = alldiseases.get(srow);
                DiseaseInfoDAO action = new DiseaseInfoDAO();
                String message = "";
                if (action.deleteRecord(ft.getDisease_id())) {
                    message = "record is deleted from database";
                    bindTableDetails();
                } else {
                    message = "record does not remove from database" + action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        srow = -1;
    }

    public void editRecord() {
        if (srow != -1 && alldiseases != null && srow < alldiseases.size()) {
            CommonOperations.openInternalFrame(getDesktopPane(), new AddDiseaseDetails(alldiseases.get(srow)));
            dispose();
        }
    }
    public void bindTableDetails() {
        alldiseases = new DiseaseInfoDAO().getAllRecord();
        String[] col_name = {"Disease id", "Disease name", "Description"};
        Object[][] records = null;
        if (alldiseases != null && alldiseases.size() > 0) {
            records = new Object[alldiseases.size()][col_name.length];
            int i = 0;
            for (DiseaseInfoTo rt : alldiseases) {
                records[i] = new Object[]{rt.getDisease_id(), rt.getDisease_name(), rt.getDescription()};
                i++;
            }
        } else {
            records = new Object[1][col_name.length];
            records[0] = new Object[]{"no records found", "no records found", "no records found"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, col_name) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabledisease.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabledisease = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Disease Details");

        tabledisease.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledisease.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablediseaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledisease);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablediseaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablediseaseMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int point = tabledisease.rowAtPoint(evt.getPoint());
            tabledisease.getSelectionModel().setSelectionInterval(point, point);
            srow = tabledisease.getSelectedRow();
            popup.show(tabledisease, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tablediseaseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledisease;
    // End of variables declaration//GEN-END:variables
}
