/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.FloorInfoDAO;
import model.to.FloorInfoTo;
import utility.CommonOperations;

/**
 *
 * @author HP
 */
public class ViewFloor extends javax.swing.JInternalFrame {

    List<FloorInfoTo> allfloors;
    private int srow;
    private JPopupMenu popup;

    public ViewFloor() {
        initComponents();
        setSize(1000, 600);
        setLocation(350, 150);
        bindTableDetails();
        srow = -1;
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete Record");
        deleteitem.setFont(new Font("Arial", Font.BOLD, 20));
        JMenuItem edititem = new JMenuItem("Edit Record");
        edititem.setFont(new Font("Arial", Font.BOLD, 20));
        try {
            ImageIcon icon1;
            icon1 = new ImageIcon(getClass().getResource("/adminui/delete.png"));
            ImageIcon icon2;
            icon2 = new ImageIcon(getClass().getResource("/adminui/edit.png"));
            deleteitem.setIcon(icon1);
            edititem.setIcon(icon2);
        } catch (Exception ex) {
        }
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        edititem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }

    public void deleteRecord() {
        if (srow != -1 && allfloors != null && srow < allfloors.size()) {
            int result = JOptionPane.showConfirmDialog(this, "are you sure you want to remove this record?", "Message from system", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                FloorInfoTo ft = allfloors.get(srow);
                FloorInfoDAO action = new FloorInfoDAO();
                String message = "";
                if (action.deleteRecord(ft.getFloor_id())) {
                    message = "record is deleted from database";
                    bindTableDetails();
                } else {
                    message = "record does not remove from database" + action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        srow = -1;
    }

    public void editRecord() {
        if (srow != -1 && allfloors != null && srow < allfloors.size()) {
            CommonOperations.openInternalFrame(getDesktopPane(), new AddFloorDetails(allfloors.get(srow)));
            dispose();
        }
    }

    public void bindTableDetails() {
        allfloors = new FloorInfoDAO().getAllRecord();
        String[] col_names = {"Floor ID", "FLoor Type"};
        Object[][] record = null;
        if (allfloors != null && allfloors.size() > 0) {
            record = new Object[allfloors.size()][col_names.length];
            int i = 0;
            for (FloorInfoTo ft : allfloors) {
                record[i] = new Object[]{ft.getFloor_id(), ft.getFloor_type()};
                i++;
            }
        } else {
            record = new Object[1][col_names.length];
            record[0] = new Object[]{"NO records", "No records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(record, col_names) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablefloor.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablefloor = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Floor Details");

        tablefloor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablefloor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablefloorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablefloor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablefloorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablefloorMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int point = tablefloor.rowAtPoint(evt.getPoint());
            tablefloor.getSelectionModel().setSelectionInterval(point, point);
            srow = tablefloor.getSelectedRow();
            popup.show(tablefloor, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tablefloorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablefloor;
    // End of variables declaration//GEN-END:variables
}
